runtime: python
service: admodel-flexi-app
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
  python_version: 3.7
# manual_scaling:
#   instances: 1
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10