steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-serverless-project-374110/demo-app-cloudrun', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-serverless-project-374110/demo-app-cloudrun']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'demo-app-cloudrun', '--image', 'gcr.io/gcp-serverless-project-374110/demo-app-cloudrun', '--region', 'us-east1']
images:
- gcr.io/gcp-serverless-project-374110/demo-app-cloudrun